paytm.payment:
  config:
    merchantId: Your merchantId
    merchantKey: Your merchantKey
    channelId: WEB
    website: WEBSTAGING
    industryTypeId: Education
    paytmUrl:  https://securegw-stage.paytm.in/order/process
    callbackUrl: http://localhost:9090/pgresponse
    details:
      MID: YOUR MID
      CHANNEL_ID: WEB
      INDUSTRY_TYPE_ID: Education
      WEBSITE: WEBSTAGING
      CALLBACK_URL: YOUR CALLBACK_URL
